# Logistics Regression OOP Version (Multiclass: One-vs-all)

### Penulis: Patuan P. Tampubolon

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np

class LogisticRegression:
    
    def __init__(self, alpha=0.01, num_iter = 1000):
        self.alpha = alpha
        self.num_iter = num_iter
        
    # method utama
    def fit(self,x,y):
        x = self.__addintercept(x) # 4.2 menyesuaikan data pada model
        n, y = self.__relabel_data(y) # 4.2 menyesuaikan data pada model
        self.theta_dict = {} # dictionary, untuk menyimpan theta masing-masing kelas
        for n_class in range(n):
            self.theta = np.zeros(x.shape[1]) # 4.3 menginisialisasi theta
            for i in range(self.num_iter): # gradient descent 
                z = np.dot(x, self.theta)  # 4.4 menghitung nilai z
                h = self.__sigmoid(z)      # 4.5 menghitung h
                gradient = np.dot(x.T, (h - y[:,n_class])) / y[:,n_class].size # 4.6 menghitung gradient
                self.theta = self.theta - self.alpha * gradient # 4.7 mengupdate theta
                loss = cost(h, y[:,n_class]).mean() # 4.8 menghitung cost
                print('loss: {}'.format(loss))
            self.theta_dict[n_class] = self.theta
                
    def predict(self, Xt):
        Xt = self.__addintercept(Xt) # diberi intercept 4.9
        n = len(self.theta_dict) # banyak kelas 4.9
        pred = np.zeros(len(Xt)*n).reshape(len(Xt),n) # pred_all yang diinisialisasi nilainya 0
        for i in range(n):
            z = np.dot(Xt, self.theta_dict[i]) #4.9
            h = self.__sigmoid(z) # 4.9
            pred[:,i] = h # 4.9 prediksi berupa peluang
        pred_max = np.zeros(len(pred)) # mencari peluang yang paling minimum, diinisialisasi dengan 0
        for j in range(len(pred)):
            rr = np.where(pred[j,:] == max(pred[j,:])) #4.10 mencari peluang yang maksimum
            pred_max[j] = rr[0][0] # 4.0 menentukan kelas
        return pred_max
    
    # tools
    def __addintercept(self, x):
        return np.concatenate((np.ones((len(x))).reshape(-1,1), x),axis = 1)
    
    def __relabel_data(self, y):
        label = list(set(y))
        relabeled_data = np.zeros(len(y)*len(label)).reshape(len(y),len(label))
        for i in range(len(label)):
            relabeled_data[y==label[i],i] = 1
        return (len(label),relabeled_data)
    
    def __sigmoid(self, z):
        return 1/(1+np.exp(-z))
    
    def __cost(self, h, y):
        return (-y * np.log(h) - (1 - y) * np.log(1 - h)) / y.size

### Load data

In [5]:
iris = datasets.load_iris()

In [6]:
X = iris.data
X[1:10]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [11]:
m1 = LogisticRegression(alpha=0.01, num_iter = 10000)

In [12]:
m2 = LogisticRegression(alpha = 0.1, num_iter = 100000)

In [13]:
m1.fit(X_train, y_train)

In [14]:
m1.theta_dict

{0: array([ 0.33257038,  0.52360747,  1.82630697, -2.83353293, -1.28838617]),
 1: array([ 0.77940509,  0.55020007, -1.64977672,  0.45059787, -1.32612439]),
 2: array([-1.15027908, -2.06321111, -1.92491251,  3.06132525,  2.78996077])}

In [16]:
m1.theta_dict[0] # theta untuk prediksi kelas 0

array([ 0.33257038,  0.52360747,  1.82630697, -2.83353293, -1.28838617])

In [17]:
m1.theta_dict[1] # theta untuk prediksi kelas 1

array([ 0.77940509,  0.55020007, -1.64977672,  0.45059787, -1.32612439])

In [18]:
m1.theta_dict[2] # theta untuk prediksi kelas 2

array([-1.15027908, -2.06321111, -1.92491251,  3.06132525,  2.78996077])

In [19]:
m2.fit(X_train, y_train)

In [20]:
m2.theta_dict

{0: array([ 0.69699367,  1.129944  ,  3.92085784, -6.16716271, -2.94257759]),
 1: array([ 6.41678993, -0.27163532, -2.39835765,  1.16548719, -2.44073534]),
 2: array([-15.750317  ,  -3.43199495,  -5.08605626,   6.78434117,
         10.92076498])}

In [21]:
p1 = m1.predict(X_test)
p1

array([1., 0., 2., 1., 1., 0., 0., 1., 2., 2., 1., 1., 0., 2., 0., 2., 0.,
       1., 2., 0., 1., 0., 0., 1., 2., 1., 0., 1., 2., 0.])

In [22]:
p2 = m2.predict(X_test)
p2

array([1., 0., 2., 1., 1., 0., 0., 1., 2., 2., 1., 1., 0., 2., 0., 2., 0.,
       1., 2., 0., 1., 0., 0., 1., 2., 1., 0., 1., 2., 0.])

In [23]:
y_test

array([1, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 1, 0, 2, 0, 2, 0, 1, 2, 0, 1, 0,
       0, 1, 2, 1, 0, 1, 2, 0])

In [24]:
len(y_test)

30

In [25]:
sum(p1 == y_test)

30

In [26]:
sum(p2 == y_test)

30