# Logistics Regression OOP Version (Multiclass: softmax)

### Penulis: Patuan P. Tampubolon

In [206]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [207]:
import numpy as np

class LogisticRegression:
    
    def __init__(self, alpha=0.01, num_iter = 1000, verbose = False):
        self.alpha = alpha
        self.num_iter = num_iter
        self.verbose = verbose
        
    # method utama
    def fit(self,x,y):
        x = self.__addintercept(x)
        y = self.__relabel_data(y)
        self.theta = np.zeros(x.shape[1]*y.shape[1]).reshape(x.shape[1],y.shape[1])
        for i in range(self.num_iter):
            z = np.dot(x, self.theta)
            h = self.__softmax(z)
            gradient = np.dot(x.T, (h - y)) / y.shape[0]
            self.theta = self.theta - self.alpha * gradient
            loss = self.__cost(h, y).mean()
            if(self.verbose):
                print('loss: {}'.format(loss))
                
    def predict(self, Xt):
        Xt = self.__addintercept(Xt) # diberi intercept 4.9
        pred = self.__softmax(np.dot(Xt,self.theta))
        pred_max = np.zeros(len(pred))
        for i in range(len(pred)):
            rr = np.where(pred [i,:] == max(pred[i,:]))
            pred_max[i] = rr[0][0]
        return pred_max
    
    # tools
    def __addintercept(self, x):
        return np.concatenate((np.ones((len(x))).reshape(-1,1), x),axis = 1)
    
    def __relabel_data(self, y):
        label = list(set(y))
        relabeled_data = np.zeros(len(y)*len(label)).reshape(len(y),len(label))
        for i in range(len(label)):
            relabeled_data[y==label[i],i] = 1
        return relabeled_data
    
    def __softmax(self, z):
        z -= np.max(z)
        sm = (np.exp(z).T / np.sum(np.exp(z),axis=1)).T
        return sm
    
    def __cost(self, h, y):
        return np.mean(np.sum(-y * np.log(h) - (1 - y) * np.log(1 - h),axis=1))

### Load data

In [208]:
iris = datasets.load_iris()

In [209]:
X = iris.data
X[1:10]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [210]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [211]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [212]:
m1 = LogisticRegression(alpha=0.01, num_iter = 10000)

In [213]:
m2 = LogisticRegression(alpha = 0.1, num_iter = 100000)

In [214]:
m1.fit(X_train, y_train)

In [215]:
m1.theta

array([[ 0.42811032,  0.74251443, -1.17062475],
       [ 0.89983826,  0.62423194, -1.5240702 ],
       [ 2.03503745, -0.0822755 , -1.95276195],
       [-2.82926464, -0.1072688 ,  2.93653344],
       [-1.33066112, -1.07758853,  2.40824965]])

In [216]:
m2.fit(X_train, y_train)

In [217]:
m2.theta

array([[  1.28079274,  10.72149806, -12.0022908 ],
       [  2.74824695,  -0.01924004,  -2.72900691],
       [  5.22041275,   0.05679376,  -5.27720651],
       [ -7.47971589,   0.1884063 ,   7.29130959],
       [ -3.83469312,  -3.9727539 ,   7.80744702]])

In [218]:
p1 = m1.predict(X_test)
p1

array([2., 0., 2., 2., 0., 2., 0., 0., 2., 1., 1., 2., 2., 1., 0., 1., 2.,
       1., 0., 0., 2., 2., 0., 1., 0., 0., 2., 1., 1., 0.])

In [219]:
p2 = m2.predict(X_test)
p2

array([2., 0., 2., 2., 0., 2., 0., 0., 2., 1., 1., 2., 2., 1., 0., 1., 2.,
       1., 0., 0., 2., 2., 0., 1., 0., 0., 2., 1., 1., 0.])

In [220]:
y_test

array([2, 0, 2, 2, 0, 2, 0, 0, 2, 1, 1, 2, 2, 1, 0, 1, 2, 1, 0, 0, 2, 2,
       0, 1, 0, 0, 2, 1, 1, 0])

In [221]:
len(y_test)

30

In [222]:
sum(p1 == y_test)

30

In [223]:
sum(p2 == y_test)

30